export const timeZones = [
  { value: "Etc/GMT+12", label: "(GMT-12:00) International Date Line West" },
  { value: "Pacific/Midway", label: "(GMT-11:00) Midway" },
  { value: "Pacific/Honolulu", label: "(GMT-10:00) Hawaii" },
  { value: "America/Anchorage", label: "(GMT-09:00) Alaska" },
  {
    value: "America/Los_Angeles",
    label: "(GMT-08:00) Pacific Time (US & Canada)",
  },
  { value: "America/Denver", label: "(GMT-07:00) Mountain Time (US & Canada)" },
  { value: "America/Chicago", label: "(GMT-06:00) Central Time (US & Canada)" },
  {
    value: "America/New_York",
    label: "(GMT-05:00) Eastern Time (US & Canada)",
  },
  { value: "America/Caracas", label: "(GMT-04:30) Caracas" },
  { value: "America/Halifax", label: "(GMT-04:00) Atlantic Time (Canada)" },
  { value: "America/St_Johns", label: "(GMT-03:30) Newfoundland" },
  { value: "America/Sao_Paulo", label: "(GMT-03:00) Brasilia" },
  { value: "Atlantic/Azores", label: "(GMT-01:00) Azores" },
  { value: "Europe/London", label: "(GMT+00:00) Greenwich Mean Time, London" },
  {
    value: "Europe/Berlin",
    label: "(GMT+01:00) Berlin, Rome, Stockholm, Vienna",
  },
  {
    value: "Europe/Istanbul",
    label: "(GMT+02:00) Athens, Bucharest, Istanbul",
  },
  { value: "Asia/Riyadh", label: "(GMT+03:00) Kuwait, Riyadh" },
  { value: "Asia/Tehran", label: "(GMT+03:30) Tehran" },
  { value: "Asia/Dubai", label: "(GMT+04:00) Abu Dhabi, Muscat" },
  { value: "Asia/Kabul", label: "(GMT+04:30) Kabul" },
  { value: "Asia/Karachi", label: "(GMT+05:00) Islamabad, Karachi" },
  {
    value: "Asia/Kolkata",
    label: "(GMT+05:30) Chennai, Kolkata, Mumbai, New Delhi",
  },
  { value: "Asia/Kathmandu", label: "(GMT+05:45) Kathmandu" },
  { value: "Asia/Dhaka", label: "(GMT+06:00) Dhaka" },
  { value: "Asia/Bangkok", label: "(GMT+07:00) Bangkok, Hanoi, Jakarta" },
  {
    value: "Asia/Hong_Kong",
    label: "(GMT+08:00) Hong Kong, Beijing, Singapore",
  },
  { value: "Asia/Tokyo", label: "(GMT+09:00) Osaka, Sapporo, Tokyo" },
  { value: "Australia/Adelaide", label: "(GMT+09:30) Adelaide" },
  {
    value: "Australia/Sydney",
    label: "(GMT+10:00) Canberra, Melbourne, Sydney",
  },
  { value: "Asia/Magadan", label: "(GMT+11:00) Magadan, Solomon Is." },
  { value: "Pacific/Auckland", label: "(GMT+12:00) Auckland, Wellington" },
]
